num1 = int(input ("Enter first number:"))
num2 = int(input ("Enter second number:"))
print("Result:", num1 + num2 )
print("Result:", num1 - num2 )
print("Result:", num1 * num2 )
print("Result:", round (num1/ num2) )